name: emoji_picker
description: A Flutter package that provides an Emoji Keyboard widget.
version: 0.0.2
author: Jeff Gugelmann <gugelmann.jeff@gmail.com>
homepage: https://github.com/JeffG05/emoji_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


